# Database connection
url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=project
password=minh123
driver=com.mysql.cj.jdbc.Driver

# Path to your changelog
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml

# Classpath (comma-separated list)
classpath=./target/classes;C:/Users/minze/.gradle/caches/modules-2/files-2.1/mysql/mysql-connector-java/8.0.19/9af69ef0f68eae737351ff55c0ba6e23a06826a5/mysql-connector-java-8.0.19.jar

# Logging & Hub
logLevel=info
liquibase.hub.mode=off
