# Database connection
url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=project
password=minh123
driver=com.mysql.cj.jdbc.Driver

# Path to your changelog
changeLogFile=db/changelog/db.changelog-master.xml
searchPath=src/main/resources

# Classpath (comma-separated list)
classpath=./target/classes;C:/Users/minze/.m2/repository/com/mysql/mysql-connector-j/8.2.0/mysql-connector-j-8.2.0.jar

# Logging & Hub
logLevel=info
liquibase.hub.mode=off
