spring.application.name=ecommerce

# =========================================================
# DATABASE CONFIGURATION
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=project
spring.datasource.password=minh123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# SWAGGER CONFIGURATION
# =========================================================
springdoc.swagger-ui.path=/docs

# =========================================================
# LOGGING CONFIGURATION
# =========================================================
# Hiện log màu sắc cho dễ nhìn
spring.output.ansi.enabled=ALWAYS

# Mức độ log cho code của bạn (DEBUG sẽ hiện chi tiết hơn INFO)
logging.level.com.minzetsu.ecommerce=DEBUG


# =========================================================
# HIBERNATE / JPA CONFIGURATION
# =========================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================================================
# LIQUIBASE CONFIGURATION
# =========================================================
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# =========================================================
# ERROR HANDLING
# =========================================================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# =========================================================
# CUSTOM APPLICATION PROPERTIES
# =========================================================
days = 7
limit = 20
admin-endpoint = /api/admin
user-endpoint = /api/users/me
