# Dev overrides
logging.level.com.minzetsu.ecommerce=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-binding-errors=always
management.endpoint.health.show-details=always
